// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/5/28 0:37:38
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/yasudajun/Desktop/nail-salon-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yasudajun/Desktop/nail-salon-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yasudajun/Desktop/nail-salon-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yasudajun/Desktop/nail-salon-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yasudajun/Desktop/nail-salon-app/plugins/**/*.{js,ts,mjs}","/Users/yasudajun/Desktop/nail-salon-app/composables/**/*.{js,ts,mjs}","/Users/yasudajun/Desktop/nail-salon-app/utils/**/*.{js,ts,mjs}","/Users/yasudajun/Desktop/nail-salon-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yasudajun/Desktop/nail-salon-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/yasudajun/Desktop/nail-salon-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/yasudajun/Desktop/nail-salon-app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;